-- Role: soccer_dba
-- DROP ROLE IF EXISTS soccer_dba;

CREATE ROLE soccer_dba WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:vCWIdOvsU4IicJT1/TFyvQ==$a1iKSWiEzoCqhLIi+HmIKb7HbuzfFDZx76HXONFrqq0=:ET0R/tV3QBvkIWfAH/aFtZzxSWLOXBmeEwCQF02PfHk=';

-- SCHEMA: soccer

-- DROP SCHEMA IF EXISTS soccer ;

CREATE SCHEMA IF NOT EXISTS soccer
    AUTHORIZATION soccer_dba;

GRANT ALL ON SCHEMA soccer TO postgres;

GRANT ALL ON SCHEMA soccer TO soccer_dba;